server:
  port: ${SERVER_PORT:5001}
  tomcat:
    threads:
      max: ${MAX_TOMCAT_THREADS:10}
    max-connections: ${MAX_TOMCAT_CONNECTIONS:20}

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://192.168.88.222:5432/telethon}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      leak-detection-threshold: ${HIKARI_LEAK_DETECTION_THRESHOLD:60000}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:20}
      max-lifetime: ${HIKARI_MAX_LIFETIME:600000}
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
    ollama:
      base-url: http://192.168.88.222:11434

content:
  directory: D://tg_logs/